// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: blog.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "blog";

export interface FindOneByIdRequest {
  id: number;
}

export interface Blog {
  id: number;
  title: string;
  author: string;
  /** change to json */
  body: string;
}

export const BLOG_PACKAGE_NAME = "blog";

export interface BlogServiceClient {
  findOneById(request: FindOneByIdRequest, ...rest: any): Observable<Blog>;
}

export interface BlogServiceController {
  findOneById(request: FindOneByIdRequest, ...rest: any): Promise<Blog> | Observable<Blog> | Blog;
}

export function BlogServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findOneById"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("BlogService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("BlogService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BLOG_SERVICE_NAME = "BlogService";
