// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v6.33.2
// source: blog.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";
import { Struct } from "./google/protobuf/struct.interface";

export const protobufPackage = "blog";

export interface FindOneByIdRequest {
  id: number;
}

export interface Blog {
  id: number;
  title: string;
  author: string;
  body: { [key: string]: any } | undefined;
}

export const BLOG_PACKAGE_NAME = "blog";

wrappers[".google.protobuf.Struct"] = { fromObject: Struct.wrap, toObject: Struct.unwrap } as any;

export interface BlogServiceClient {
  findOneById(request: FindOneByIdRequest): Observable<Blog>;
}

export interface BlogServiceController {
  findOneById(request: FindOneByIdRequest): Promise<Blog> | Observable<Blog> | Blog;
}

export function BlogServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findOneById"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("BlogService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("BlogService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BLOG_SERVICE_NAME = "BlogService";
